/**
 * Merged rows into a database.
 *
 * Writes SQL rather than talking to D1 directly, for a reason that is not
 * squeamishness: `wrangler d1 execute --file` does the bulk load in one command,
 * and a Worker cannot do it at all — the import path is CLI-only. From inside a
 * Worker there is only the binding API and batched inserts, which is the right
 * tool for the recurring refresh and the wrong one for the first load of 190,000
 * rows.
 *
 * So this produces a file. `wrangler d1 execute places --file=.build/load.sql`
 * applies it locally or remotely, and the same file is what a stranger runs to
 * stand up their own copy — which is also how ODbL's share-alike gets satisfied
 * by something a person can actually use.
 *
 * Statements are batched rather than one-per-row because D1 rejects a statement
 * over its length limit and accepts very few very large ones far faster than very
 * many small ones. 500 is comfortably inside both bounds.
 */

import { join } from "node:path"
import { createWriteStream, mkdirSync } from "node:fs"
import { records } from "../lib/ndjson.ts"
import type { MergedPlace } from "./merge.ts"

const OUT = process.env.PLACES_OUT ?? ".build"
const BATCH = 500

/** SQLite string literal. Doubling the quote is the whole of the escaping. */
const q = (v: string) => `'${v.replace(/'/g, "''")}'`
const n = (v: number | null | undefined) => (v === undefined || v === null || Number.isNaN(v) ? "NULL" : String(v))
const s = (v: string | null | undefined) => (v === undefined || v === null || v === "" ? "NULL" : q(v))

export async function load(argv: string[]): Promise<void> {
  const tiers = argv.filter((a) => !a.startsWith("--"))
  const wanted = tiers.length ? tiers : ["countries", "subdivisions", "cities"]
  mkdirSync(OUT, { recursive: true })
  const path = join(OUT, "load.sql")
  const out = createWriteStream(path)

  out.write("-- Generated by `places load`. Apply with:\n")
  out.write("--   wrangler d1 execute places --file=.build/load.sql\n")
  out.write("-- Data licence: ODbL-1.0. See LICENSE-DATA before redistributing.\n\n")
  out.write("PRAGMA foreign_keys=OFF;\nBEGIN TRANSACTION;\n")
  // Idempotent: re-running a load must replace rather than accumulate, or a
  // refresh doubles the table and every count silently becomes wrong.
  out.write("DELETE FROM name;\nDELETE FROM place;\n\n")

  let places = 0
  let names = 0
  const flush = (table: string, columns: string, rows: string[]) => {
    if (!rows.length) return
    out.write(`INSERT INTO ${table} (${columns}) VALUES\n${rows.join(",\n")};\n`)
    rows.length = 0
  }

  /**
   * Every place before any name. Two passes, not one interleaved.
   *
   * `name.place_id` references `place.id`, and batching both in one pass emits a
   * name batch whenever it fills — which can be before the batch holding its
   * place. D1 rejected the whole file with `FOREIGN KEY constraint failed` and
   * named no row, which is a long way from the actual mistake. `PRAGMA
   * foreign_keys=OFF` would also have silenced it, and would have been the wrong
   * fix: the constraint was right and the order was wrong.
   *
   * A second pass over NDJSON is cheap because nothing is held in memory.
   */
  const placeRows: string[] = []
  for (const tier of wanted) {
    for await (const p of records<MergedPlace>(join(OUT, `${tier}.merged.ndjson`))) {
      places++
      placeRows.push(
        `(${q(p.id)},${q(p.type)},${q(p.pivot)},${s(p.parent)},${s(p.country)},${n(p.lat)},${n(p.lon)},${n(p.population)},${s(p.wikidata)})`,
      )
      if (placeRows.length >= BATCH) {
        flush("place", "id,type,pivot,parent_id,country_code,lat,lon,population,wikidata_id", placeRows)
      }
    }
  }
  flush("place", "id,type,pivot,parent_id,country_code,lat,lon,population,wikidata_id", placeRows)

  const nameRows: string[] = []
  for (const tier of wanted) {
    for await (const p of records<MergedPlace>(join(OUT, `${tier}.merged.ndjson`))) {
      for (const nm of p.names) {
        names++
        nameRows.push(`(${q(p.id)},${q(nm.locale)},${q(nm.value)},${q(nm.source)},${q(nm.kind)})`)
      }
      if (nameRows.length >= BATCH) flush("name", "place_id,locale,value,source,kind", nameRows)
    }
  }
  flush("name", "place_id,locale,value,source,kind", nameRows)

  out.write("\nCOMMIT;\nPRAGMA foreign_keys=ON;\n")
  await new Promise<void>((resolve) => out.end(resolve))

  console.log(`  ${places.toLocaleString()} places, ${names.toLocaleString()} names → ${path}`)
  console.log("\nApply it with:")
  console.log("  wrangler d1 execute places --local  --file=.build/load.sql")
  console.log("  wrangler d1 execute places --remote --file=.build/load.sql")
}
