/**
 * Merged rows into a database.
 *
 * Writes SQL rather than talking to D1 directly, for a reason that is not
 * squeamishness: `wrangler d1 execute --file` does the bulk load in one command,
 * and a Worker cannot do it at all — the import path is CLI-only. From inside a
 * Worker there is only the binding API and batched inserts, which is the right
 * tool for the recurring refresh and the wrong one for the first load of 190,000
 * rows.
 *
 * So this produces a file. `wrangler d1 execute places --file=.build/load.sql`
 * applies it locally or remotely, and the same file is what a stranger runs to
 * stand up their own copy — which is also how ODbL's share-alike gets satisfied
 * by something a person can actually use.
 *
 * Statements are batched rather than one-per-row because D1 rejects a statement
 * over its length limit and accepts very few very large ones far faster than very
 * many small ones. 500 is comfortably inside both bounds.
 */

import { join } from "node:path"
import { createWriteStream, mkdirSync } from "node:fs"
import { gunzipSync } from "node:zlib"
import { existsSync, readFileSync } from "node:fs"
import { resolve as resolvePath } from "node:path"
import { records } from "../lib/ndjson.ts"
import type { MergedPlace } from "./merge.ts"

const OUT = process.env.PLACES_OUT ?? ".build"
const BATCH = 500

/** SQLite string literal. Doubling the quote is the whole of the escaping. */
const q = (v: string) => `'${v.replace(/'/g, "''")}'`
const n = (v: number | null | undefined) => (v === undefined || v === null || Number.isNaN(v) ? "NULL" : String(v))
const s = (v: string | null | undefined) => (v === undefined || v === null || v === "" ? "NULL" : q(v))

/**
 * What the last publish held, keyed by place, as a comparable string per name.
 *
 * The basis for a delta. `data/` is what we last vouched for and what the diff
 * already compares against, so reusing it costs nothing and cannot drift from the
 * thing being compared.
 */
function publishedNames(tier: string): Map<string, string> | null {
  const path = resolvePath(import.meta.dirname, "../..", "data", `${tier}.ndjson.gz`)
  if (!existsSync(path)) return null
  const out = new Map<string, string>()
  for (const line of gunzipSync(readFileSync(path)).toString("utf8").trimEnd().split("\n")) {
    if (!line) continue
    const p = JSON.parse(line) as MergedPlace
    // Order-independent so a reshuffle is not mistaken for a change.
    out.set(
      p.id,
      p.names.map((n) => `${n.locale}\u0001${n.value}\u0001${n.kind}\u0001${n.source}`).sort().join("\u0002"),
    )
  }
  return out
}

export async function load(argv: string[]): Promise<void> {
  const tiers = argv.filter((a) => !a.startsWith("--"))
  const wanted = tiers.length ? tiers : ["countries", "subdivisions", "cities"]
  const delta = argv.includes("--delta")
  mkdirSync(OUT, { recursive: true })
  const path = join(OUT, "load.sql")
  const out = createWriteStream(path)

  out.write("-- Generated by `places load`. Apply with:\n")
  out.write("--   wrangler d1 execute places --file=.build/load.sql\n")
  out.write("-- Data licence: ODbL-1.0. See LICENSE-DATA before redistributing.\n\n")
  /**
   * No BEGIN TRANSACTION, and this is not an oversight.
   *
   * Local D1 accepts it. Remote D1 refuses: "To execute a transaction, please use
   * the state.storage.transaction() APIs instead of the SQL BEGIN TRANSACTION" —
   * because a D1 database is a Durable Object and it coalesces writes itself. So
   * a file that loads perfectly against `--local` fails against `--remote`, which
   * is the worst kind of divergence: the one you find after the local run gave
   * you confidence.
   *
   * The load is therefore not atomic. It is made safe by ordering instead —
   * deletes first, every place, then every name — so a partial failure leaves a
   * subset rather than a database with names pointing at places that are not
   * there.
   */
  // Idempotent: re-running a load must replace rather than accumulate, or a
  // refresh doubles the table and every count silently becomes wrong.
  // A delta leaves `place` alone — places change far less often than names, and
  // deleting them would cascade into every name row we are trying not to touch.
  // `coverage` is always rebuilt: it is derived, small, and wrong if stale.
  out.write(delta ? "DELETE FROM coverage;\n\n" : "DELETE FROM coverage;\nDELETE FROM name;\nDELETE FROM place;\n\n")

  let places = 0
  let names = 0
  let changed = 0
  let unchanged = 0
  const flush = (table: string, columns: string, rows: string[]) => {
    if (!rows.length) return
    out.write(`INSERT INTO ${table} (${columns}) VALUES\n${rows.join(",\n")};\n`)
    rows.length = 0
  }

  /**
   * Every place before any name. Two passes, not one interleaved.
   *
   * `name.place_id` references `place.id`, and batching both in one pass emits a
   * name batch whenever it fills — which can be before the batch holding its
   * place. D1 rejected the whole file with `FOREIGN KEY constraint failed` and
   * named no row, which is a long way from the actual mistake. `PRAGMA
   * foreign_keys=OFF` would also have silenced it, and would have been the wrong
   * fix: the constraint was right and the order was wrong.
   *
   * A second pass over NDJSON is cheap because nothing is held in memory.
   */
  const placeRows: string[] = []
  for (const tier of wanted) {
    for await (const p of records<MergedPlace>(join(OUT, `${tier}.merged.ndjson`))) {
      places++
      placeRows.push(
        `(${q(p.id)},${q(p.type)},${q(p.pivot)},${s(p.parent)},${s(p.country)},${n(p.lat)},${n(p.lon)},${n(p.population)},${s(p.wikidata)})`,
      )
      if (delta) { placeRows.length = 0; continue }
      if (placeRows.length >= BATCH) {
        flush("place", "id,type,pivot,parent_id,country_code,lat,lon,population,wikidata_id", placeRows)
      }
    }
  }
  flush("place", "id,type,pivot,parent_id,country_code,lat,lon,population,wikidata_id", placeRows)

  const nameRows: string[] = []
  for (const tier of wanted) {
    /**
     * In delta mode, only places whose names actually moved.
     *
     * A full load rewrites 1.2 million name rows and five million row-writes to
     * remote D1 — three to six minutes — to add names for a handful of languages.
     * Almost every row is identical to the one it replaces.
     *
     * So compare against the last publish and touch only what changed. The
     * DELETEs are per place rather than table-wide, which is what makes this a
     * delta rather than a smaller full load.
     */
    const before = delta ? publishedNames(tier) : null
    if (delta && !before) {
      console.log(`  ${tier}: nothing published to compare against — writing in full`)
    }
    for await (const p of records<MergedPlace>(join(OUT, `${tier}.merged.ndjson`))) {
      if (before) {
        const now = p.names
          .map((n) => `${n.locale}\u0001${n.value}\u0001${n.kind}\u0001${n.source}`)
          .sort()
          .join("\u0002")
        if (before.get(p.id) === now) { unchanged++; continue }
        changed++
        out.write(`DELETE FROM name WHERE place_id = ${q(p.id)};\n`)
      }
      for (const nm of p.names) {
        names++
        nameRows.push(`(${q(p.id)},${q(nm.locale)},${q(nm.value)},${q(nm.source)},${q(nm.kind)})`)
      }
      if (nameRows.length >= BATCH) flush("name", "place_id,locale,value,source,kind", nameRows)
    }
  }
  flush("name", "place_id,locale,value,source,kind", nameRows)

  /**
   * Coverage, computed here rather than per request.
   *
   * One INSERT ... SELECT at load time replaces a 1.18-million-row aggregate on
   * every call to /api/matrix and /api/locales. Written as SQL rather than
   * computed in TypeScript so that anyone who loads these dumps into their own
   * SQLite gets the same table without running our ETL.
   */
  out.write(`
INSERT INTO coverage (locale, type, named, real)
SELECT n.locale, p.type, COUNT(*),
       SUM(CASE WHEN n.kind IN ('translated','native','override') THEN 1 ELSE 0 END)
  FROM name n JOIN place p ON p.id = n.place_id
 WHERE n.locale != 'und'
 GROUP BY n.locale, p.type;
`)
  out.write("\n-- no COMMIT: see the note above on remote D1 and transactions\n")
  await new Promise<void>((resolve) => out.end(resolve))

  if (delta) {
    console.log(`  delta: ${changed.toLocaleString()} places changed, ${unchanged.toLocaleString()} untouched`)
    console.log(`  ${names.toLocaleString()} name rows to write → ${path}`)
  } else {
    console.log(`  ${places.toLocaleString()} places, ${names.toLocaleString()} names → ${path}`)
  }
  console.log("\nApply it with:")
  console.log("  wrangler d1 execute places --local  --file=.build/load.sql")
  console.log("  wrangler d1 execute places --remote --file=.build/load.sql")
}
