/**
 * The whole cycle, in one command, in the right order.
 *
 * Everything this does was already possible and I ran it by hand perhaps thirty
 * times today: pull, merge, diff, load, apply, publish, deploy. Every run was an
 * opportunity to do them out of order, skip the diff, forget to re-export `data/`
 * after a fix, or load without pulling first — and I did most of those at least
 * once. The 76MB blob, the stale `data/`, the twenty-five languages of labels
 * discarded: all of them are steps-in-sequence failures rather than logic errors.
 *
 * A CLI that requires a person to remember an order is a CLI with a bug in it.
 *
 * ## The order, and why it is this order
 *
 *   pull    the scheduled refresh's findings, or the merge silently drops them
 *   merge   every source resolved by precedence — the only thing that decides a name
 *   diff    against what was last published, before anything is written
 *   load    a delta by default, because a full rewrite is 81MB to change 64 rows
 *   apply   local first, then remote: local is where a broken file is cheap
 *   publish data/ re-exported, which is both the ODbL obligation and the next diff's baseline
 *   record  what this publish changed, so "when did that name move" has an answer
 *   deploy  because the registry items are assets and are stale until it happens
 *   verify  against the deployed service, because local D1 and remote D1 disagree
 *
 * The last three were once a printed reminder — `Synced. \`bun x wrangler deploy\`
 * if the Worker itself changed.` The condition made it worse than nothing: the
 * registry items are regenerated by this command and served as assets, so a run
 * that changes no Worker code still leaves `/r/places-picker.json` serving the
 * previous component with nothing failing. Reading that reminder correctly and
 * answering "no" is how a stale registry item ships.
 *
 * Stops on a loss unless told not to. A shrinking dataset is sometimes correct —
 * filtering the deprecated country aliases removed 23 places and that was the fix
 * — but it should be a decision rather than something noticed a week later.
 */

import { spawnSync } from "node:child_process"
import { existsSync } from "node:fs"
import { join, resolve as resolvePath } from "node:path"

const OUT = process.env.PLACES_OUT ?? ".build"
const ROOT = resolvePath(import.meta.dirname, "../..")

function run(label: string, argv: string[], opts: { quiet?: boolean; env?: Record<string, string> } = {}): string {
  process.stdout.write(`\n── ${label}\n`)
  const res = spawnSync(argv[0], argv.slice(1), {
    cwd: ROOT,
    encoding: "utf8",
    env: opts.env ? { ...process.env, ...opts.env } : process.env,
    maxBuffer: 256 * 1024 * 1024,
    stdio: opts.quiet ? ["inherit", "pipe", "pipe"] : "inherit",
  })
  if (res.status !== 0) {
    if (opts.quiet) console.error(res.stdout ?? "", res.stderr ?? "")
    throw new Error(`${label} failed`)
  }
  return res.stdout ?? ""
}

const places = (...args: string[]) => ["bun", "scripts/places.ts", ...args]
const wrangler = (...args: string[]) => ["bun", "x", "wrangler", ...args]

export async function sync(argv: string[]): Promise<void> {
  const full = argv.includes("--full")
  const force = argv.includes("--force")
  const dry = argv.includes("--dry-run")
  const skipRemote = argv.includes("--local-only")
  const noDeploy = argv.includes("--no-deploy")

  console.log("Syncing: pull → merge → diff → load → apply → publish")
  if (dry) console.log("(--dry-run: stopping after the diff)")

  /**
   * Pull first, always.
   *
   * The weekly refresh writes what it finds to R2 as well as to D1. Merging
   * without pulling rebuilds from local sources only, and `load` opens by
   * deleting — so a week of scheduled work disappears with nothing said. This
   * ordering is the whole reason the command exists.
   */
  run("pulling the refresh's findings", places("pull"))

  run("merging every source by precedence", places("merge"))

  // Before anything is written. A diff after the load is a post-mortem.
  const diff = run("what changed", places("diff"), { quiet: true })
  process.stdout.write(diff)

  /**
   * A loss stops the run unless somebody says otherwise.
   *
   * Parsed from the diff's own output rather than recomputed, so the number that
   * gates the run is the number the human is shown. If those two ever disagree
   * the gate is worthless.
   */
  const lost = [...diff.matchAll(/−(\d+)/g)].map((m) => Number(m[1])).reduce((a, b) => a + b, 0)
  if (lost > 0 && !force) {
    console.error(`\n  STOPPING: this build loses ${lost} place(s).`)
    console.error("  Sometimes right — filtering the deprecated country aliases removed 23 and that was the fix.")
    console.error("  Look at the diff above, then re-run with --force if it is what you meant.")
    process.exitCode = 1
    return
  }
  if (dry) { console.log("\n  --dry-run: nothing written."); return }

  run(full ? "writing a full load" : "writing a delta", places("load", ...(full ? [] : ["--delta"])))

  if (!existsSync(join(ROOT, OUT, "load.sql"))) throw new Error("no load.sql — did `load` write anything?")

  /**
   * Local before remote, always.
   *
   * A malformed load file costs seconds locally and minutes plus a half-applied
   * production database remotely. Remote D1 also refuses things local D1 accepts
   * — `BEGIN TRANSACTION`, most memorably — so local is a real check and not a
   * formality.
   */
  run("applying locally", wrangler("d1", "execute", "places", "--local", "--file=.build/load.sql"))
  if (!skipRemote) {
    run("applying to the deployed database", wrangler("d1", "execute", "places", "--remote", "--file=.build/load.sql", "-y"))
  }

  /**
   * Publishing last, and never skipped.
   *
   * `data/` is two things at once: the ODbL obligation, and the baseline the next
   * diff compares against. Forgetting it means the repository claims to publish a
   * database it is not serving *and* the next diff reports changes that already
   * shipped. It drifted exactly once and nothing noticed for an hour.
   */
  /**
   * `-n`, so an unchanged build produces an unchanged file.
   *
   * gzip writes the source filename and its modification time into the header, so
   * `gzip -9 -c` gave three new binary blobs on every run — byte-for-byte
   * different, semantically identical. `git status` was dirty after every sync,
   * `git diff --stat` said `Bin 11297863 -> 11297863 bytes`, and a real change
   * looked exactly like a no-op re-run.
   *
   * That matters here more than it usually would: `data/` is the ODbL artefact
   * *and* the baseline the next diff compares against, so it is committed often
   * and read carefully. Noise in it trains people to commit without looking.
   *
   * `-n` omits both fields and makes the output a function of the input.
   */
  run("publishing data/", [
    "sh",
    "-c",
    "for t in countries subdivisions cities; do gzip -9 -n -c .build/$t.merged.ndjson > data/$t.ndjson.gz; done",
  ])

  /**
   * The record of this publish, appended once the publish has actually happened.
   *
   * After `data/` rather than before: the history says what was *released*, and a
   * run that stopped at the load would otherwise leave an entry describing a
   * database nobody is serving.
   *
   * `places diff` above wrote the comparison to `.build/change.json`; this folds
   * it in. It is the same numbers the human was shown, kept rather than recomputed
   * — for the same reason the loss gate parses the printed diff instead of doing
   * its own arithmetic.
   */
  run("recording what this publish changed", places("history", "--append"))

  /**
   * Rebuild the served registry items before the checks, not after.
   *
   * They embed the component's source, so they go stale the moment it changes —
   * and a stale one installs an old component with no error at all. Regenerating
   * here means the drift check that follows is testing something current rather
   * than failing on a step somebody forgot.
   */
  run("rebuilding the registry items", places("registry"))

  run("checks", ["bun", "run", "check"])

  if (skipRemote || noDeploy) {
    console.log(`\n  Synced locally. Not deployed (${skipRemote ? "--local-only" : "--no-deploy"}).`)
    return
  }

  /**
   * Deploying is part of the cycle, not a note at the end of it.
   *
   * This used to print `Synced. \`bun x wrangler deploy\` if the Worker itself
   * changed.` — a step a person had to remember, conditional on a judgement they
   * had to make. Both halves are wrong.
   *
   * The judgement is wrong because the registry items are *assets*. `places
   * registry` regenerates them two steps above, and until a deploy they exist
   * only on this machine: the deployed `/r/places-picker.json` keeps serving the
   * previous component, and `shadcn add` keeps installing it, with nothing
   * failing anywhere. That is the stale-registry-item bug this project has
   * already shipped once, reachable by doing everything right and stopping one
   * step early. "If the Worker itself changed" reads as "no" in exactly that case.
   *
   * The remembering is wrong for the reason this whole command exists. I ran the
   * pipeline by hand perhaps thirty times and got the order wrong most ways it
   * can be got wrong; today I ran `sync` and then forgot the deploy, twice.
   *
   * Placed after the checks, so a failing test stops the deploy rather than
   * following it.
   */
  run("deploying", wrangler("deploy"))

  /**
   * And then ask the deployed service whether it works.
   *
   * Local D1 and remote D1 disagree — remote refuses `BEGIN TRANSACTION`, the
   * asset binding behaves differently under `wrangler dev` — so a green local
   * suite is evidence about this machine. The service tests take six seconds
   * against production and are the only thing that has ever caught the edges:
   * the missing CORS, the 500 on every subdivision, the query-string `limit`.
   *
   * A deploy that is not verified is a deploy somebody else discovers.
   */
  run("checking the deployed service", ["bun", "x", "vitest", "run", "tests/api/service.test.ts"], {
    env: { PLACES_URL: "https://shadcn-places.gedw99.workers.dev" },
  })

  console.log("\n  Synced, deployed and verified.")
}
