/**
 * Where the data comes from, and what each source costs to use.
 *
 * One table rather than URLs scattered through the ETL, because the licence is
 * not metadata here — it is the reason this repository is public and the reason
 * the data and the code carry different terms. A source added without its licence
 * beside it is how an obligation gets missed.
 *
 * `weight` is what it costs to stage. It is here so that `places stage` can say
 * what it is about to download before it downloads it, on a laptop that may not
 * want 1.2GB today.
 */

import ALIAS_TABLE from "../../src/api/locale-aliases.json"

/** CLDR's language alias table, generated by `places aliases`. 500 entries, 6KB. */
const LOCALE_ALIASES: Record<string, string> = ALIAS_TABLE.aliases

export type Licence = "Unicode" | "CC BY 4.0" | "ODbL-1.0" | "CC0"

/** How a name was arrived at. Precedence is defined by KIND_RANK below. */
export type Kind = "override" | "translated" | "native" | "romanised" | "transliterated"

export interface Source {
  id: string
  licence: Licence
  /** Approximate staged size, for the warning `stage` prints. */
  weight: string
  /** Absent for Wikidata, which is queried rather than downloaded. */
  url?: string
  /** Why it is here, and what it is NOT good for. */
  note: string
  /**
   * The exact wording the licence requires, and what the check looks for.
   *
   * The check used to search for a fragment of the source id, which passed for
   * the wrong reason and then failed for the wrong reason: crediting
   * "© OpenStreetMap contributors" — the precise form ODbL asks for — did not
   * satisfy a test looking for the string "osm". An id is an internal name; a
   * credit is a promise to somebody else, and the two should not be confused by
   * the thing that verifies the promise.
   */
  credit?: string
  /**
   * Share-alike sources oblige us to publish what we derive. Marked so the repo
   * check can assert the derived rows are actually committed, rather than the
   * ETL being published while the database it produces is not.
   */
  shareAlike?: true
}

export const SOURCES: readonly Source[] = [
  {
    id: "cldr",
    licence: "Unicode",
    weight: "nothing — it is in the runtime",
    credit: "CLDR",
    note: "Country names in every locale ICU carries, via Intl.DisplayNames. Complete there, and that is narrower than it sounds — ICU ships about a hundred locales, so Wu, Cantonese, Egyptian Arabic, Tatar and 136 other languages holding real place names had zero country names until Wikidata was asked for them by ISO code (`places labels --countries`). Also stops at country level: CLDR's subdivision data is English-only, three entries in every other locale.",
  },
  {
    id: "geonames-cities",
    licence: "CC BY 4.0",
    weight: "3MB",
    url: "https://download.geonames.org/export/dump/cities5000.zip",
    credit: "GeoNames",
    note:
      "The city inventory: which places exist, their romanised pivot, coordinates, population. Not a translation source — its cross-language coverage collapses below 100k people, which is what Wikidata is for. " +
      "Moved from cities15000 to cities5000 on 2026-09-10: a venue is as likely to be in a town of 8,000 as a city of 20,000, and 'full world coverage' is as much about which places exist as about how many languages name them. " +
      "Expect the percentages to fall when this changes — a smaller town has fewer translations, so a wider inventory looks like a regression in every coverage figure while being an improvement in every practical sense.",
  },
  {
    id: "geonames-admin1",
    licence: "CC BY 4.0",
    weight: "150KB",
    url: "https://download.geonames.org/export/dump/admin1CodesASCII.txt",
    credit: "GeoNames",
    note: "3,865 first-level subdivisions worldwide, English/ASCII.",
  },
  {
    id: "geonames-alternates",
    licence: "CC BY 4.0",
    weight: "193MB zipped, ~900MB expanded",
    url: "https://download.geonames.org/export/dump/alternateNames.zip",
    credit: "GeoNames",
    note: "Every language in one file, which is why extraction keeps them all: filtering would be extra work, not less. Also carries pseudo-languages — `link`, `unlc`, `wkdt` — which are not languages and must be excluded from counts. `wkdt` is the Wikidata ID, a second join key.",
  },
  {
    id: "dr5hn",
    licence: "ODbL-1.0",
    shareAlike: true,
    weight: "44MB",
    url: "https://raw.githubusercontent.com/dr5hn/countries-states-cities-database/master/json/states.json",
    credit: "dr5hn",
    note:
      "5,308 subdivisions with translations in 19 languages at 100%, plus `native` at 100%. The best subdivision source measured. Its cities carry no translations at all despite the columns existing. " +
      "Its translations are machine-produced and occasionally translate a place name as the common noun it collides with: Brazil's state of Acre is `エーカー` in Japanese and `فدان` in Arabic — both the unit of area. California and England are correct in every language checked, so this is a tail rather than a pattern, " +
      "but it is why `kind: translated` here means 'a source called this a translation' and never 'a human has read it'. Four subdivision ids also appear twice (French overseas territories); the merge keeps the first and counts the rest.",
  },
  {
    id: "osm-subdivisions",
    licence: "ODbL-1.0",
    shareAlike: true,
    weight: "3MB, one Overpass query",
    url: "https://overpass-api.de/api/interpreter",
    credit: "OpenStreetMap",
    note:
      "OpenStreetMap admin relations carrying an ISO 3166-2 code — 4,373 of them, which is most of the world's first-level subdivisions. " +
      "Added because it covers precisely the languages dr5hn does not: th, vi, id, sw, he, el, bn, ms. Where dr5hn has a language OSM rarely beats it, so this fills rather than competes. " +
      "The join is exact and needs no matching: OSM's ISO3166-2 tag *is* our subdivision id. Same ODbL terms as dr5hn, so it adds no new obligation.",
  },
  {
    id: "overrides",
    licence: "CC0",
    weight: "nothing — it is in this repository",
    note: "Corrections we make ourselves, in overrides.json, committed. The only source that is not re-derivable and therefore the only one a rebuild must preserve. Ranks above everything: upstream improving should flow in automatically, and upstream being wrong is what this is for.",
  },
  {
    id: "wikidata",
    licence: "CC0",
    credit: "Wikidata",
    weight: "nothing to download, minutes of SPARQL",
    note: "The only real cross-language city source: 84% ja and 89% ru for cities of 15k-100k, where GeoNames manages 7% and 20%. Joined on P1566, the GeoNames ID. Queried per language, so it is the one source with a language policy of its own.",
  },
]

/**
 * Which name wins when several sources name the same place in the same language.
 *
 * A rule rather than a judgement, so that a re-run is deterministic and so that a
 * transliteration added later is replaced automatically the day a real name
 * appears upstream — rather than someone having to notice.
 */
export const KIND_RANK: Record<Kind, number> = {
  /**
   * A human said so, and a rebuild must not argue.
   *
   * Everything else here is derived from a source and is therefore disposable:
   * re-run the ETL and it comes back the same or better. An override is the one
   * kind that cannot be re-derived, because the knowledge that produced it —
   * that Brazil's state of Acre is not the unit of area — exists nowhere upstream.
   *
   * It outranks `translated` deliberately. Upstream improving is the normal case
   * and should flow in automatically; upstream being *wrong* is the case an
   * override exists for, and deferring to it would defeat the purpose.
   */
  override: 4,
  translated: 3,
  native: 2,
  /** Generated, so it must lose to any real name that later appears upstream. */
  transliterated: 1,
  romanised: 0,
}

/**
 * Tags GeoNames puts in the language column that are not languages.
 *
 * Counting these as languages makes `link` and `unlc` look like two of the most
 * widely spoken on earth. `wkdt` is kept out of names for the same reason and
 * read separately, as a join key.
 */
export const NOT_LANGUAGES = new Set([
  "link", "unlc", "wkdt", "iata", "icao", "faac", "abbr", "abbreviation", "post", "phon", "fr_1793", "unofficial",
])

/**
 * Does this look like a language tag at all?
 *
 * GeoNames puts more than languages in its `isolanguage` column, and the
 * exclusion list above only catches the ones somebody has noticed. The coverage
 * matrix found the rest the moment it listed every locale in the database:
 * `1556--1922`, `1836-1848`, `1889--1921` — historical name periods — sitting
 * beside Japanese as though they were languages somebody reads.
 *
 * A shape test catches the class rather than the instances. Two or three letters,
 * optionally with subtags, which is what BCP-47 and ISO 639-3 both produce.
 *
 * Deliberately permissive about three-letter codes: `abq` is Abaza, `adx` is Amdo
 * Tibetan, `aig` is Antigua Creole. They look like noise and are real languages
 * with real speakers, and dropping them because they are unfamiliar would be the
 * same mistake in the opposite direction.
 */
export const isLanguageTag = (tag: string): boolean =>
  /^[a-z]{2,3}(-[A-Za-z0-9]{2,8})*$/.test(tag) && !NOT_LANGUAGES.has(tag)

/**
 * One language, one tag — because two halves of one language help nobody.
 *
 * Measured against the deployed database: **Filipino was split in two.** 2,543
 * names under `tl` and 1,148 under `fil`, and the request negotiation is
 * `locale IN (locale, base)` — so `fil` never reaches `tl` and neither reaches
 * the other. A Filipino reader asking for `fil` got **0% subdivisions** while 446
 * real Filipino subdivision names sat in the table under `tl`.
 *
 * That is the `tl`/`fil` trap for the third time in this project: once in an
 * application's `Intl` calls, once in this service's endonym lookup, and now in
 * the data itself. Four more languages were split the same way — `no`/`nb`,
 * `sh`/`sr`, `als`/`gsw`, `bh`/`bho`.
 *
 * ## The table is CLDR's, not mine
 *
 * The first version of this was twelve entries typed out after finding the
 * Filipino split. CLDR ships **five hundred**, maintained, with a reason on each
 * — and agreed with eleven of my twelve. `places aliases` generates the compact
 * form into `src/api/locale-aliases.json`; a repo test regenerates it and fails
 * if they diverge.
 *
 * Writing that list by hand would have been the third time in this file: fifty
 * hand-typed non-Latin scripts that were missing thirty-nine, and now this.
 *
 * ## Where our sources disagree with CLDR, and it is not CLDR that is wrong
 *
 * Two entries below override the generated table. Both were verified against the
 * actual values rather than assumed, and both exist because our sources use a tag
 * differently from the standard:
 *
 *   `als` — CLDR says Tosk Albanian, so its alias is `sq`. Our values are
 *   "Kanton Jura", "Wil SG", "Veyrier GE": **Wikipedia uses `als` for Alemannic
 *   German**, and applying CLDR's alias would have filed German names under
 *   Albanian, where the script check would have called them real translations.
 *
 *   `no` — CLDR has no alias for it at all, correctly: `no` is the Norwegian
 *   macrolanguage. Every value our sources give it is Bokmål, which is `nb`, and
 *   leaving them apart means two half-populated Norwegians.
 */
const SOURCE_ALIAS_OVERRIDES: Record<string, string> = {
  als: "gsw",
  no: "nb",
}

/**
 * The tag a language's names are stored under.
 *
 * Applied by the merge, so the database holds one tag per language, and by the
 * Worker, so a caller asking for `tl` is answered from `fil`. Both call this, and
 * it reads a committed table rather than an `Intl` call — `Intl` gives different
 * answers in Bun, Node and workerd, and the two callers must never disagree.
 *
 * The region and script subtags survive: `pt-BR` is not `pt`, and the request
 * negotiation already falls back from one to the other.
 */
export function canonicalLocale(tag: string): string {
  /**
   * Applied until it stops moving, because aliases chain.
   *
   * CLDR maps `nor` → `no`, and our own override maps `no` → `nb`. A single pass
   * left `nor` sitting at `no` — a tag that is itself an alias — so a source
   * emitting `nor` would have re-split Norwegian one hop further out than the
   * split this function exists to heal. Found by asserting idempotency over the
   * whole table rather than by spotting it.
   *
   * Five iterations is far past anything CLDR contains and makes a malformed
   * table a fixed point rather than a hang.
   */
  let current = tag
  for (let i = 0; i < 5; i++) {
    const [base, ...rest] = current.split("-")
    const canonical =
      SOURCE_ALIAS_OVERRIDES[current] ??
      SOURCE_ALIAS_OVERRIDES[base] ??
      LOCALE_ALIASES[current] ??
      LOCALE_ALIASES[base]
    if (!canonical) return current
    // `sh-Latn` must not become `sr-Latn-Latn`: an alias that already carries a
    // script or region replaces the whole tag rather than just its base.
    const next = canonical.includes("-") ? canonical : [canonical, ...rest].join("-")
    if (next === current) return current
    current = next
  }
  return current
}

export const byId = (id: string): Source => {
  const found = SOURCES.find((s) => s.id === id)
  if (!found) throw new Error(`unknown source: ${id}. Known: ${SOURCES.map((s) => s.id).join(", ")}`)
  return found
}

/**
 * Which languages are written in a script where a Latin string is not a lesser
 * translation but an unreadable one.
 *
 * Not a judgement about the language — about the script. A Dutch reader given
 * "Ourinhos" is reading Dutch. A Thai reader given "Ourinhos" is reading nothing,
 * and a Thai reader given "Changwat Bueng Kan" — which GeoNames really does tag
 * as `th` — is reading a transliteration somebody labelled a translation.
 *
 * ## This was a list of fifty and it was missing thirty-nine
 *
 * Hand-written, defensible, and wrong the moment the data grew past the languages
 * I happened to think of. Measured against the loaded database: 39 locales with
 * more than 150 names each — Egyptian Arabic with 12,681, Tatar with 8,177, Wu,
 * Cantonese, Chechen, Bashkir, Odia — hold names that are 100% non-Latin and were
 * classified as Latin-script because nobody had typed them here.
 *
 * That had two consequences, and the second is worse than the first:
 *
 *   `/api/matrix` counted their Latin fallbacks as real names, overstating them
 *   `resolve()` in merge.ts never demoted a Latin value to `romanised` for them,
 *   because the demotion is gated on this very set — so the honesty check that
 *   this whole project is organised around was simply not running for 39
 *   languages
 *
 * ## CLDR already knows, so ask it
 *
 * `Intl.Locale#maximize` resolves a language tag to its likely script from
 * CLDR's own data, in every runtime this code runs in, with no list to maintain.
 * Checked against 187 locales in the loaded database: it agrees with the observed
 * script of their names 178 times.
 *
 * The nine it does not, plus the four it has no answer for, are below. Each is a
 * real disagreement rather than a bug, and each earns its line.
 */
const SCRIPT_OVERRIDES: Record<string, "Latn" | "NonLatn"> = {
  /**
   * Written in Latin here, whatever CLDR's likely script says.
   *
   * The Min and Hakka varieties reach us romanised — Pe̍h-ōe-jī and Bàng-uâ-cê —
   * so every name we hold for them is Latin even though CLDR's likely script is
   * Han. Karakalpak and Crimean Tatar officially changed to Latin alphabets and
   * CLDR still reports Cyrillic as likely. Ladino and Wolaytta are written both
   * ways and our sources use Latin.
   *
   * All seven verified against the data: 96–100% of their names are Latin.
   */
  nan: "Latn", cdo: "Latn", hak: "Latn", kaa: "Latn", crh: "Latn", lad: "Latn", wal: "Latn",
  /**
   * Not written in Latin, and CLDR has no likely script to offer.
   *
   * `Intl.Locale#maximize` returns nothing for these four, and the fallback for
   * "unknown" is Latin — which would overstate them exactly the way the old list
   * did. Western Punjabi is Shahmukhi, Buryat and Meadow Mari are Cyrillic,
   * Bihari is Devanagari. All four measured at 0% Latin in the loaded database.
   *
   * Keyed by the **canonical** tag, because that is what the merge stores: CLDR
   * folds `pnb` into `lah`, `bxr` into `bua`, `mhr` into `chm` and `bh` into
   * `bho`, so an override written against the source tag would never be found.
   * The original spellings are listed beside them so the next person searching
   * for "pnb" lands here.
   */
  lah: "NonLatn",   // pnb, Western Punjabi — Shahmukhi
  bua: "NonLatn",   // bxr, Buryat — Cyrillic
  chm: "NonLatn",   // mhr, Meadow Mari — Cyrillic
  bho: "NonLatn",   // bh, Bhojpuri — Devanagari
}

/**
 * The script CLDR considers likely for a language tag.
 *
 * `undefined` when CLDR has no opinion, which is a different thing from Latin
 * and is why the caller decides what to do about it.
 */
export function scriptOf(locale: string): string | undefined {
  try {
    return new Intl.Locale(locale).maximize().script
  } catch {
    // Not a parseable language tag. `und` and the pseudo-locales land here.
    return undefined
  }
}

/**
 * Would a reader of this locale be served by a Latin string?
 *
 * Unknown resolves to `true`, and that is the direction that overstates rather
 * than the one that hides work — a locale wrongly called Latin looks better than
 * it is, which somebody will notice, where one wrongly called non-Latin quietly
 * consumes a refresh budget it does not need. The overrides above exist so that
 * "unknown" stays a small set rather than a hiding place.
 *
 * **Runtime-dependent, and therefore not to be called from the Worker.** See
 * `classifyScript` below.
 */
export function isLatinLocale(locale: string): boolean {
  const override = SCRIPT_OVERRIDES[locale] ?? SCRIPT_OVERRIDES[locale.split("-")[0]]
  if (override) return override === "Latn"
  const script = scriptOf(locale)
  return script === undefined || script === "Latn"
}

/**
 * The same question, answered from the names themselves where there are enough.
 *
 * ## Why the data outranks CLDR here
 *
 * `Intl` disagrees with itself across runtimes. Measured over the 710 locales in
 * this database, Bun's ICU and Node's ICU give different answers for 30 of them:
 * Node knows Western Punjabi is Shahmukhi and Buryat is Cyrillic where Bun
 * returns nothing, and Bun knows Urdu is Nastaliq where Node says plain Arabic.
 * workerd is a third ICU and will be a third answer.
 *
 * That matters because three different parts of this system asked the question:
 * the merge (Bun) decided whether to demote a Latin value to `romanised`, the
 * tests (Node) asserted on the result, and the Worker (workerd) reported it as
 * coverage. Three runtimes, one question, and no guarantee they agree — which is
 * the same shape as the divergence between the deployed database and the local
 * build that lost 3,025 Thai names.
 *
 * So it is resolved once, in the ETL, and written into the `coverage` table.
 * Everything downstream reads a column.
 *
 * ## And why the names are better evidence than a lookup anyway
 *
 * A language's likely script is a fact about the language; what we hold is a
 * fact about our sources. Where we have a few hundred names, they settle it
 * directly and unanimously: Thai, Japanese, Chinese, Korean, Russian, Hindi,
 * Arabic, Hebrew, Greek, Georgian, Armenian, Bengali and Tamil are each 0% Latin
 * across tens of thousands of names. There is nothing for a lookup table to add.
 *
 * Below the threshold there is not enough to conclude anything, and CLDR is the
 * better guess than a coin flip.
 */
export const SCRIPT_EVIDENCE_MINIMUM = 150

export function classifyScript(locale: string, observed?: { n: number; latin: number }): boolean {
  if (observed && observed.n >= SCRIPT_EVIDENCE_MINIMUM) return observed.latin / observed.n > 0.5
  return isLatinLocale(locale)
}

/**
 * Is this string written in Latin letters?
 *
 * ASCII, the Latin-1 and Latin Extended blocks, and the punctuation and digits
 * that legitimately appear inside a place name. Anything outside them means the
 * value carries the script it claims, which is all this needs to decide.
 */
export const isLatinScript = (value: string): boolean => /^[\p{Script=Latin}\p{P}\p{N}\p{Zs}\p{M}]+$/u.test(value)
